# Generated by Django 4.1.7 on 2023-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_asset_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Garments', 'Garments')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
