# Generated by Django 4.1.7 on 2023-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_about_company_active_company_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('SE', 'SE'), ('TecLead', 'TecLead')], max_length=100),
        ),
    ]
